### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by shiraji** [shiraji/common-custom-channel#1]
URL: https://plugins.jetbrains.com/docs/marketplace/custom-release-channels.html

- [x] Create option that set/unset common custom release channels https://github.com/JetBrains/intellij-community/blob/817804427e116e5176e94a8f9b066c872ce0170e/platform/platform-impl/src/com/intellij/ide/plugins/PluginHostsConfigurable.java#L270-L276
- [x] Add link to jump the setting dialog
- [x] Setup CI (github actions???)
